owner: gigapipehq
repo: healthcheck
sites:
  - name: US-3C-API
    url: $US_3C_API
  - name: US-3C-AUTH
    url: $US_3C_AUTH
  - name: US-3C-QRYN
    url: $US_3C_QRYN
    expectedStatusCodes:
      - 401
  - name: US-3C-APP
    url: $US_3C_APP
  - name: EU-SM-API
    url: $EU_SM_API
  - name: EU-SM-AUTH
    url: $EU_SM_AUTH
  - name: EU-SM-QRYN
    url: $EU_SM_QRYN
    expectedStatusCodes:
      - 401
  - name: EU-SM-APP
    url: $EU_SM_APP
